"""Add icon cols to enquiry

Revision ID: 0672d35c0e46
Revises: fc8338a7bb8c
Create Date: 2025-12-23 22:51:09.947673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0672d35c0e46'
down_revision: Union[str, None] = 'fc8338a7bb8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enquiry', sa.Column('am_icon', sa.String(), nullable=True))
    op.execute("UPDATE enquiry SET am_icon = ''")
    op.alter_column('enquiry', 'am_icon', nullable=False)
    
    op.add_column('enquiry', sa.Column('pm_icon', sa.String(), nullable=True))
    op.execute("UPDATE enquiry SET pm_icon = ''")
    op.alter_column('enquiry', 'pm_icon', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('enquiry', 'pm_icon')
    op.drop_column('enquiry', 'am_icon')
    # ### end Alembic commands ###
