"""Add bus to student

Revision ID: 2618f781e590
Revises: 62d39456c8af
Create Date: 2025-12-25 20:43:22.846256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2618f781e590'
down_revision: Union[str, None] = '62d39456c8af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('am_bus_id', sa.UUID(), nullable=True))
    op.add_column('student', sa.Column('pm_bus_id', sa.UUID(), nullable=True))
    op.create_foreign_key('fk_student_am_bus_id', 'student', 'bus', ['am_bus_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_student_pm_bus_id', 'student', 'bus', ['pm_bus_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_student_pm_bus_id', 'student', type_='foreignkey')
    op.drop_constraint('fk_student_am_bus_id', 'student', type_='foreignkey')
    op.drop_column('student', 'pm_bus_id')
    op.drop_column('student', 'am_bus_id')
    # ### end Alembic commands ###
