"""Enquiry add is_favourite and change email sent name

Revision ID: 26c5f08bf560
Revises: 8c8c0f9e037e
Create Date: 2025-06-18 21:15:33.520836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26c5f08bf560'
down_revision: Union[str, None] = '8c8c0f9e037e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('enquiry', 'email_sent', new_column_name='is_email_sent')
    op.add_column('enquiry', sa.Column('is_favourite', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.alter_column('enquiry', 'is_favourite', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('enquiry', 'is_email_sent', new_column_name='email_sent')
    op.drop_column('enquiry', 'is_favourite')
    # ### end Alembic commands ###
