"""remove enquiry status enum

Revision ID: 28cab067ce29
Revises: a6f79060c086
Create Date: 2025-12-27 20:56:38.285838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28cab067ce29'
down_revision: Union[str, None] = 'a6f79060c086'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TYPE IF EXISTS enquirystatus")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE enquirystatus AS ENUM ('TBC', 'OPTION', 'SENT', 'REGISTRATION', 'REJECTED')")
    # ### end Alembic commands ###
