"""Add bus to location

Revision ID: 48abcd710664
Revises: 62d39456c8af
Create Date: 2025-12-27 02:47:06.468121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '48abcd710664'
down_revision: Union[str, None] = '62d39456c8af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('location', sa.Column('bus_id', sa.UUID(), nullable=True))
    op.create_foreign_key('fk_location_bus_id', 'location', 'bus', ['bus_id'], ['id'], ondelete='SET NULL')
    op.drop_column('location', 'time_reached')
    op.drop_column('location', 'position')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('location', sa.Column('position', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('location', sa.Column('time_reached', postgresql.TIME(), autoincrement=False, nullable=True))
    op.drop_constraint('fk_location_bus_id', 'location', type_='foreignkey')
    op.drop_column('location', 'bus_id')
    # ### end Alembic commands ###
