"""add enquiry table

Revision ID: 4c5849da328a
Revises: 9b5db70fc99a
Create Date: 2024-12-20 18:29:21.430983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c5849da328a'
down_revision: Union[str, None] = '9b5db70fc99a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enquiry',
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('phone_no', sa.String(), nullable=False),
    sa.Column('block', sa.String(), nullable=False),
    sa.Column('remark', sa.String(), nullable=False),
    sa.Column('fare', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('TBC', 'SENT', 'RECEIVED', name='enquirystatus'), nullable=True),
    sa.Column('school_id', sa.UUID(), nullable=True),
    sa.Column('am_location_id', sa.UUID(), nullable=True),
    sa.Column('pm_location_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.Column('updated_on', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['am_location_id'], ['location.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['pm_location_id'], ['location.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['school_id'], ['school.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('enquiry')
    op.execute("DROP TYPE enquirystatus")
    # ### end Alembic commands ###
