"""Add new table Bus

Revision ID: 62d39456c8af
Revises: b45a63a32a9f
Create Date: 2025-12-24 17:43:37.016661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62d39456c8af'
down_revision: Union[str, None] = 'b45a63a32a9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bus',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('am_plate_no', sa.String(), nullable=False),
    sa.Column('am_capacity', sa.Integer(), nullable=False),
    sa.Column('pm_plate_no', sa.String(), nullable=False),
    sa.Column('pm_capacity', sa.Integer(), nullable=False),
    sa.Column('colour', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_on', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bus')
    # ### end Alembic commands ###
