"""add final year to school

Revision ID: 70865c97aba0
Revises: a8b30ad71a67
Create Date: 2025-01-26 18:02:56.014898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70865c97aba0'
down_revision: Union[str, None] = 'a8b30ad71a67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('school', sa.Column('is_final_year', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('school', 'is_final_year')
    # ### end Alembic commands ###
