"""Map enquiry status to string in DB

Revision ID: 80309dba360a
Revises: 86d43e03e666
Create Date: 2025-12-09 22:04:52.491393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '80309dba360a'
down_revision: Union[str, None] = '86d43e03e666'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('enquiry', 'status',
               existing_type=postgresql.ENUM('TBC', 'OPTION', 'SENT', 'REGISTRATION', 'REJECTED', name='enquirystatus'),
               type_=sa.String(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('enquiry', 'status',
               existing_type=sa.String(),
               type_=postgresql.ENUM('TBC', 'OPTION', 'SENT', 'REGISTRATION', 'REJECTED', name='enquirystatus'),
               existing_nullable=True,
               postgresql_using='status::enquirystatus')
    # ### end Alembic commands ###
