"""Add email attachment key to school

Revision ID: 86d43e03e666
Revises: 512c3d4925c1
Create Date: 2025-06-22 19:49:39.526958

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86d43e03e666'
down_revision: Union[str, None] = '512c3d4925c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('school', sa.Column('email_attachment_key', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('school', 'email_attachment_key')
    # ### end Alembic commands ###
