"""School should be non nullable in enquiry

Revision ID: 8c8c0f9e037e
Revises: edb32bb06778
Create Date: 2025-06-15 22:02:20.287174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c8c0f9e037e'
down_revision: Union[str, None] = 'edb32bb06778'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('enquiry', 'school_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('enquiry', 'school_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
