"""add location table

Revision ID: 9b5db70fc99a
Revises: e286f7d521d4
Create Date: 2024-12-20 18:22:27.715394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b5db70fc99a'
down_revision: Union[str, None] = 'e286f7d521d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('location',
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('time', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('AM', 'PM', name='routetype'), nullable=False),
    sa.Column('time_reached', sa.Time(), nullable=True),
    sa.Column('position', sa.Float(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.Column('updated_on', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('location')
    op.execute('DROP TYPE routetype')
    # ### end Alembic commands ###
