"""Change type to string

Revision ID: a6f79060c086
Revises: 48abcd710664
Create Date: 2025-12-27 20:53:21.412440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a6f79060c086'
down_revision: Union[str, None] = '48abcd710664'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('location', 'type',
               existing_type=postgresql.ENUM('AM', 'PM', name='routetype'),
               type_=sa.String(),
               existing_nullable=False)
    op.execute("DROP TYPE IF EXISTS routetype")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE routetype AS ENUM ('AM', 'PM')")
    op.alter_column('location', 'type',
               existing_type=sa.String(),
               type_=postgresql.ENUM('AM', 'PM', name='routetype'),
               existing_nullable=False,
               postgresql_using='type::routetype')
    # ### end Alembic commands ###
