"""add email to school

Revision ID: a8b30ad71a67
Revises: ff920f8aeb5b
Create Date: 2025-01-26 16:24:29.077784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8b30ad71a67'
down_revision: Union[str, None] = 'ff920f8aeb5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('school', sa.Column('email', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('school', 'email')
    # ### end Alembic commands ###
