"""Add parent entity

Revision ID: aa70633ce70a
Revises: 80309dba360a
Create Date: 2025-12-11 21:47:53.066606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa70633ce70a'
down_revision: Union[str, None] = '80309dba360a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parent',
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('contact1_name', sa.String(), nullable=False),
    sa.Column('contact1_no', sa.String(), nullable=False),
    sa.Column('contact1_relationship', sa.String(), nullable=False),
    sa.Column('contact2_name', sa.String(), nullable=False),
    sa.Column('contact2_no', sa.String(), nullable=False),
    sa.Column('contact2_relationship', sa.String(), nullable=False),
    sa.Column('home_postal_code', sa.String(), nullable=False),
    sa.Column('home_unit_no', sa.String(), nullable=False),
    sa.Column('home_address', sa.String(), nullable=False),
    sa.Column('am_postal_code', sa.String(), nullable=False),
    sa.Column('am_address', sa.String(), nullable=False),
    sa.Column('pm_postal_code', sa.String(), nullable=False),
    sa.Column('pm_address', sa.String(), nullable=False),
    sa.Column('under_fas', sa.Boolean(), nullable=False),
    sa.Column('fare', sa.Integer(), nullable=False),
    sa.Column('enquiry_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_on', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['enquiry_id'], ['enquiry.id'], ondelete='Set NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('parent')
    # ### end Alembic commands ###
