"""Add icon to student

Revision ID: b442e1cfebfd
Revises: 09910c78171b
Create Date: 2026-01-07 17:18:35.440145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b442e1cfebfd'
down_revision: Union[str, None] = '09910c78171b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('icon', sa.String(), nullable=True))
    op.execute("UPDATE student SET icon = '' WHERE icon IS NULL")
    op.alter_column('student', 'icon',
                existing_type=sa.String(),
                nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student', 'icon')
    # ### end Alembic commands ###
