"""Add new fields to student

Revision ID: b45a63a32a9f
Revises: 0672d35c0e46
Create Date: 2025-12-24 01:29:09.925949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b45a63a32a9f'
down_revision: Union[str, None] = '0672d35c0e46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('am_icon', sa.String(), nullable=True))
    op.execute("UPDATE student SET am_icon = ''")
    op.alter_column('student', 'am_icon', nullable=False)
    
    op.add_column('student', sa.Column('pm_icon', sa.String(), nullable=True))
    op.execute("UPDATE student SET pm_icon = ''")
    op.alter_column('student', 'pm_icon', nullable=False)
    
    op.add_column('student', sa.Column('is_favourite', sa.Boolean(), nullable=True))
    op.execute("UPDATE student SET is_favourite = false")
    op.alter_column('student', 'is_favourite', nullable=False)
    
    op.add_column('student', sa.Column('remark', sa.String(), nullable=True))
    op.execute("UPDATE student SET remark = ''")
    op.alter_column('student', 'remark', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student', 'remark')
    op.drop_column('student', 'is_favourite')
    op.drop_column('student', 'pm_icon')
    op.drop_column('student', 'am_icon')
    # ### end Alembic commands ###
