"""add year and addresses to enquiry

Revision ID: cc8bf15c1820
Revises: e58611eb61ab
Create Date: 2025-01-30 22:07:32.766860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc8bf15c1820'
down_revision: Union[str, None] = 'e58611eb61ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enquiry', sa.Column('home_address', sa.String(), nullable=False))
    op.add_column('enquiry', sa.Column('am_address', sa.String(), nullable=False))
    op.add_column('enquiry', sa.Column('pm_address', sa.String(), nullable=False))
    op.add_column('enquiry', sa.Column('year', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('enquiry', 'year')
    op.drop_column('enquiry', 'pm_address')
    op.drop_column('enquiry', 'am_address')
    op.drop_column('enquiry', 'home_address')
    # ### end Alembic commands ###
