"""Make student status nullable

Revision ID: d9ac31fe00d2
Revises: b442e1cfebfd
Create Date: 2026-01-07 22:08:07.459761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9ac31fe00d2'
down_revision: Union[str, None] = 'b442e1cfebfd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('student', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.execute("UPDATE student SET status = NULL WHERE status = ''")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE student SET status = '' WHERE status IS NULL")
    op.alter_column('student', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
