"""Change enquiry table

Revision ID: e58611eb61ab
Revises: 70865c97aba0
Create Date: 2025-01-29 20:40:52.686393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e58611eb61ab'
down_revision: Union[str, None] = '70865c97aba0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enquiry', sa.Column('email', sa.String(), nullable=False))
    op.add_column('enquiry', sa.Column('home_postal_code', sa.String(), nullable=False))
    op.add_column('enquiry', sa.Column('home_unit_no', sa.String(), nullable=False))
    op.add_column('enquiry', sa.Column('am_postal_code', sa.String(), nullable=False))
    op.add_column('enquiry', sa.Column('pm_postal_code', sa.String(), nullable=False))
    op.drop_column('enquiry', 'date')
    op.drop_column('enquiry', 'phone_no')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enquiry', sa.Column('phone_no', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('enquiry', sa.Column('date', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('enquiry', 'pm_postal_code')
    op.drop_column('enquiry', 'am_postal_code')
    op.drop_column('enquiry', 'home_unit_no')
    op.drop_column('enquiry', 'home_postal_code')
    op.drop_column('enquiry', 'email')
    # ### end Alembic commands ###
