"""Add email_sent to school

Revision ID: edb32bb06778
Revises: 405266c66f60
Create Date: 2025-06-15 21:49:09.868965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'edb32bb06778'
down_revision: Union[str, None] = '405266c66f60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enquiry', sa.Column('email_sent', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.alter_column('enquiry', 'email_sent', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('enquiry', 'email_sent')
    # ### end Alembic commands ###
