"""Add is_favourite and rules key to school

Revision ID: fc8338a7bb8c
Revises: fd5800172779
Create Date: 2025-12-23 20:07:25.343554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc8338a7bb8c'
down_revision: Union[str, None] = 'fd5800172779'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('school', sa.Column('is_favourite', sa.Boolean(), nullable=True))
    op.execute("UPDATE school SET is_favourite = false")
    op.alter_column('school', 'is_favourite', nullable=False)
    op.add_column('school', sa.Column('rules_key', sa.String(), nullable=True))
    op.alter_column('school', 'email_attachment_key', new_column_name='price_list_key')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('school', 'price_list_key', new_column_name='email_attachment_key')
    op.drop_column('school', 'rules_key')
    op.drop_column('school', 'is_favourite')
    # ### end Alembic commands ###
