"""Add student entity

Revision ID: fd5800172779
Revises: aa70633ce70a
Create Date: 2025-12-11 22:05:54.332789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd5800172779'
down_revision: Union[str, None] = 'aa70633ce70a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student',
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('given_name', sa.String(), nullable=False),
    sa.Column('gender', sa.String(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('class_name', sa.String(), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('nric', sa.String(), nullable=False),
    sa.Column('transport_start_date', sa.Date(), nullable=False),
    sa.Column('transport_requirement', sa.String(), nullable=False),
    sa.Column('block', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.Column('am_location_id', sa.UUID(), nullable=True),
    sa.Column('pm_location_id', sa.UUID(), nullable=True),
    sa.Column('parent_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_on', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['am_location_id'], ['location.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_id'], ['parent.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pm_location_id'], ['location.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['school_id'], ['school.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student')
    # ### end Alembic commands ###
