"""add unique constraint to location

Revision ID: ff920f8aeb5b
Revises: 4c5849da328a
Create Date: 2024-12-29 21:01:50.150724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff920f8aeb5b'
down_revision: Union[str, None] = '4c5849da328a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_address_type', 'location', ['address', 'type'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_address_type', 'location', type_='unique')
    # ### end Alembic commands ###
